apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: obp-bootstrap
  namespace: k8s
subjects:
- kind: ServiceAccount
  name: obp-bootstrap
  namespace: k8s
roleRef:
  kind: Role
  name: obp-bootstrap
  apiGroup: rbac.authorization.k8s.io